name: project_welingkar
description: A Flutter version of Welingkar's Elearn Portal app.

publish_to: 'none'
version: 4.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.8
  requests: ^3.3.0
  html: ^0.14.0+3
  webview_flutter: ^0.3.22+1
  intl: ^0.16.1
  flutter_rounded_date_picker: ^1.0.5
  simple_connectivity: ^0.1.1
  url_launcher: ^5.5.2
  flutter_html: ^1.0.0
  flutter_custom_tabs: ^0.6.0
  webfeed: ^0.6.0
  photo_view: ^0.10.2
  admob_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Serif
      fonts:
        - asset: fonts/Serif.ttf
